"""Personal OpenSRE account endpoints and local storage names."""

from __future__ import annotations

OPENSRE_ACCOUNT_FILENAME = "account.json"
OPENSRE_ACCOUNT_METADATA_PATH_ENV = "OPENSRE_ACCOUNT_METADATA_PATH"
OPENSRE_ACCOUNT_TOKEN_ENV = "OPENSRE_ACCOUNT_TOKEN"
OPENSRE_ACCOUNT_LLM_BASE_PATH = "/api/llm/v1"
OPENSRE_APP_URL_DEFAULT = "https://app.opensre.com"
OPENSRE_APP_URL_DEV = "http://localhost:3000"
OPENSRE_APP_URL_ENV = "OPENSRE_APP_URL"

__all__ = [
    "OPENSRE_ACCOUNT_FILENAME",
    "OPENSRE_ACCOUNT_METADATA_PATH_ENV",
    "OPENSRE_ACCOUNT_LLM_BASE_PATH",
    "OPENSRE_ACCOUNT_TOKEN_ENV",
    "OPENSRE_APP_URL_DEFAULT",
    "OPENSRE_APP_URL_DEV",
    "OPENSRE_APP_URL_ENV",
]
