"""Aerospike environment variable names."""

from __future__ import annotations

AEROSPIKE_HOST_ENV = "AEROSPIKE_HOST"
AEROSPIKE_PORT_ENV = "AEROSPIKE_PORT"
AEROSPIKE_USERNAME_ENV = "AEROSPIKE_USERNAME"
AEROSPIKE_PASSWORD_ENV = "AEROSPIKE_PASSWORD"
AEROSPIKE_TIMEOUT_SECONDS_ENV = "AEROSPIKE_TIMEOUT_SECONDS"
AEROSPIKE_TLS_ENV = "AEROSPIKE_TLS"

__all__ = [
    "AEROSPIKE_HOST_ENV",
    "AEROSPIKE_PASSWORD_ENV",
    "AEROSPIKE_PORT_ENV",
    "AEROSPIKE_TIMEOUT_SECONDS_ENV",
    "AEROSPIKE_TLS_ENV",
    "AEROSPIKE_USERNAME_ENV",
]
