"""Keycloak environment variable names."""

from __future__ import annotations

KEYCLOAK_URL_ENV = "KEYCLOAK_URL"
KEYCLOAK_MANAGEMENT_URL_ENV = "KEYCLOAK_MANAGEMENT_URL"
KEYCLOAK_REALM_ENV = "KEYCLOAK_REALM"
KEYCLOAK_AUTH_REALM_ENV = "KEYCLOAK_AUTH_REALM"
KEYCLOAK_CLIENT_ID_ENV = "KEYCLOAK_CLIENT_ID"
KEYCLOAK_CLIENT_SECRET_ENV = "KEYCLOAK_CLIENT_SECRET"
KEYCLOAK_VERIFY_SSL_ENV = "KEYCLOAK_VERIFY_SSL"
KEYCLOAK_TIMEOUT_SECONDS_ENV = "KEYCLOAK_TIMEOUT_SECONDS"

__all__ = [
    "KEYCLOAK_AUTH_REALM_ENV",
    "KEYCLOAK_CLIENT_ID_ENV",
    "KEYCLOAK_CLIENT_SECRET_ENV",
    "KEYCLOAK_MANAGEMENT_URL_ENV",
    "KEYCLOAK_REALM_ENV",
    "KEYCLOAK_TIMEOUT_SECONDS_ENV",
    "KEYCLOAK_URL_ENV",
    "KEYCLOAK_VERIFY_SSL_ENV",
]
