"""NATS environment variable names."""

from __future__ import annotations

NATS_MONITOR_URL_ENV = "NATS_MONITOR_URL"
NATS_MONITOR_USERNAME_ENV = "NATS_MONITOR_USERNAME"
NATS_MONITOR_PASSWORD_ENV = "NATS_MONITOR_PASSWORD"
NATS_VERIFY_SSL_ENV = "NATS_VERIFY_SSL"
NATS_TIMEOUT_SECONDS_ENV = "NATS_TIMEOUT_SECONDS"

__all__ = [
    "NATS_MONITOR_PASSWORD_ENV",
    "NATS_MONITOR_URL_ENV",
    "NATS_MONITOR_USERNAME_ENV",
    "NATS_TIMEOUT_SECONDS_ENV",
    "NATS_VERIFY_SSL_ENV",
]
