"""nginx environment variable names."""

from __future__ import annotations

NGINX_HOST_ENV = "NGINX_HOST"
NGINX_PORT_ENV = "NGINX_PORT"
NGINX_SSL_ENV = "NGINX_SSL"
NGINX_VERIFY_SSL_ENV = "NGINX_VERIFY_SSL"
NGINX_USERNAME_ENV = "NGINX_USERNAME"
NGINX_PASSWORD_ENV = "NGINX_PASSWORD"
NGINX_STUB_STATUS_PATH_ENV = "NGINX_STUB_STATUS_PATH"
NGINX_API_PATH_ENV = "NGINX_API_PATH"
NGINX_ACCESS_LOG_PATH_ENV = "NGINX_ACCESS_LOG_PATH"
NGINX_ERROR_LOG_PATH_ENV = "NGINX_ERROR_LOG_PATH"
NGINX_TIMEOUT_SECONDS_ENV = "NGINX_TIMEOUT_SECONDS"

__all__ = [
    "NGINX_ACCESS_LOG_PATH_ENV",
    "NGINX_API_PATH_ENV",
    "NGINX_ERROR_LOG_PATH_ENV",
    "NGINX_HOST_ENV",
    "NGINX_PASSWORD_ENV",
    "NGINX_PORT_ENV",
    "NGINX_SSL_ENV",
    "NGINX_STUB_STATUS_PATH_ENV",
    "NGINX_TIMEOUT_SECONDS_ENV",
    "NGINX_USERNAME_ENV",
    "NGINX_VERIFY_SSL_ENV",
]
