"""YugabyteDB environment variable names."""

from __future__ import annotations

YUGABYTEDB_HOST_ENV = "YUGABYTEDB_HOST"
YUGABYTEDB_PORT_ENV = "YUGABYTEDB_PORT"
YUGABYTEDB_DATABASE_ENV = "YUGABYTEDB_DATABASE"
YUGABYTEDB_USERNAME_ENV = "YUGABYTEDB_USERNAME"
YUGABYTEDB_PASSWORD_ENV = "YUGABYTEDB_PASSWORD"
YUGABYTEDB_SSL_MODE_ENV = "YUGABYTEDB_SSL_MODE"

__all__ = [
    "YUGABYTEDB_DATABASE_ENV",
    "YUGABYTEDB_HOST_ENV",
    "YUGABYTEDB_PASSWORD_ENV",
    "YUGABYTEDB_PORT_ENV",
    "YUGABYTEDB_SSL_MODE_ENV",
    "YUGABYTEDB_USERNAME_ENV",
]
